### ISSUE TITLE
browser support

### ISSUE THREAD

**Issue by anandthakker** [mapbox/tile-reduce#25]
It should be possible to make this work in modern browsers via web workers. To do this:

 - [ ] factor out [getVectorTile](https://github.com/mapbox/tile-reduce/blob/master/worker.js#L33-L70), and provide a browser version that uses `xhr` instead of `request`.  (Note: I *think* the browser will handle the gzip transparently.)
 - [ ] use [webworkify](https://github.com/substack/webworkify) as a substitute for `child_process.fork`
 - [ ] tests (how??)

**Comment by morganherlocker** [comment]
rough xhr version ripped from some other code I had:

```js
function getVectorTile(t, url, done){
  var x = t[0];
  var y = t[1];
  var z = t[2];

  // select vector tile
  var url = tileUrl.split('{x}').join(x);
  url = url.split('{y}').join(y);
  url = url.split('{z}').join(z);

  getArrayBuffer(url, function(err, data) { 
    var vt = new VectorTile(new Pbf(new Uint8Array(data)));
    var layers = Object.keys(vt.layers);
    var fcs = []
    layers.forEach(function(layer){
      var fc = turf.featurecollection([]);
      for(var i = 0; i < vt.layers[layer].length; i++){
        fc.features.push(vt.layers[layer].feature(i).toGeoJSON(x,y,z));
      }
      fcs.push(fc)
    });
    done(null, fcs)
  });
}

function getArrayBuffer(url, callback) {
    var xhr = new XMLHttpRequest();
    xhr.open('GET', url, true);
    xhr.responseType = 'arraybuffer';
    xhr.onerror = function(e) {
        callback(e);
    };
    xhr.onload = function() {
        if (xhr.status >= 200 && xhr.status < 300 && xhr.response) {
            callback(null, xhr.response);
        } else {
            callback(new Error(xhr.statusText));
        }
    };
    xhr.send();
    return xhr;
}
```

**Comment by morganherlocker** [comment]
^ note that I have had some trouble in the past finding a solution that auto-gunzips for both node.js *and* browser. request-browser ignores gzip headers, as does node-xhr, so we'll need to do a bit of hacking around to get this to work in the same codebase.

**Comment by anandthakker** [comment]
Ack.  Another issue is that webworkify isn't gonna cut it, since it would need the web worker source at bundling time, but the worker uses this [dynamic require](https://github.com/mapbox/tile-reduce/blob/master/worker.js#L8).

**Comment by morganherlocker** [comment]
@anandthakker oof yeah. We could just specify that you have to pre-browserify a standalone script ahead of time. That would be a pretty reasonable requirement for clientside IMO.

**Comment by anandthakker** [comment]
@morganherlocker I take it all back: I do think it might be possible to use webworkify here, but it might involve some pretty weird eval stuff.

**Comment by tcql** [comment]
I was thinking on this the other day. It's interesting, but with us now relying heavily on process streams for output, this is even more complicated. Since webworkers won't have externally accessible streams for `worker.process.std*` we'd need to wrap the webworker and catch messages, redirecting to streams that exist only in the main thread.

- Find a solution for the dynamic require that @anandthakker mentioned
- Wrap webworkify or some other webworker implementations inside an object that has streams accessible under `worker.process.std*` 
- Have `worker.js` aware of whether it's forked or webworker-ed. If it's in a webworker, instead of using `process.std*` streams, have it `send` messages that have a prefix / attribute to specify whether they should be received as stream data.
- In the wrapper around webworkify, catch all messages from the webworker, and read the prefix or attribute. If the message has a prefix specifying it goes to one of the output streams, push the data to wrapper's streams. If it doesn't, actually emit the message so tilereduce can catch it

**Comment by mourner** [comment]
@anandthakker is there a real use case for TileReduce in the browser?

**Comment by mourner** [comment]
Closing as something that's not worth the effort at the moment. Let's reopen if we find some good use cases for this.

**Comment by anandthakker** [comment]
@mourner sorry to have missed this last week.  I think the use case is there, but it's not very common: it would be a way to do live / interactive analysis on vector tile data -- e.g., summing population in a user-drawn polygon (or something like that).

Anyway, I agree with leaving this closed.
