### ISSUE TITLE
Mbtiles support

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/tile-reduce#31]
We need this. Atlas.

I started here: https://github.com/mapbox/tile-reduce/pull/28

**Comment by mtirwin** [comment]
High five.

**Comment by morganherlocker** [comment]
Technically tile-reduce will already work out of the box with Atlas or a combo of Atlas and Mapbox.com. Not trying to dissuade, because it would be useful regardless; just want to point out that Atlas users can already use tile-reduce just like we do.

**Comment by MateoV** [comment]
I've continued work on supporting local mbtiles in the [`mbtiles-matt`](https://github.com/mapbox/tile-reduce/tree/mbtiles-matt) branch. It's working well but there are a couple things I'd like to add, not to mention some new tests.

This work required a bit of refactoring in order to get around concurrency issues when grabbing data in parallel across the workers. The data is now retrieved in the main thread and then sent to the workers, whose only function now is to process it.

### Changes
- Vector tile data retrieval moved to main thread
- Can specify an `mbtile` uri in `opts.tileLayers`
- Can use a combo of `url` and `mbtile` if using multiple `tileLayers`
- No rate limit on local mbtiles unless there is at least one other `url` in `tileLayers`

### To do
- Validate mbtiles?
- Catch errors such as out of zoom range or out of bounds
- Catch error if no tile exists in the mbtiles and skip/ignore (currently exits)
- Option to use mbtiles bounds as area
- Option to process all existing tiles in the mbtiles rather than use area
- Tests
- Documentation

@morganherlocker would be great to get your eyes on this when you have some free time.
cc @aaronlidman

**Comment by mourner** [comment]
This was done.
