### ISSUE TITLE
support other sources

### ISSUE THREAD

**Issue by tcql** [mapbox/tile-reduce#45]
This may end up being irrelevant depending on new architecture, but if we keep data source configuration centralized, we should think about supporting more sources. Maybe use tilelive, so supporting other sources is trivial / zero changes to tile reduce internals

Background: I'm trying to do OSM stats by country. This means that I either:

- Need to split jobs up by country, OR
- Need to know what country a tile is in during each worker's step of reduce. 

Using Geojson-vt and Natural Earth Admin 0 boundaries, I can easily figure out which countries are present in a tile, but currently that requires me to do `geojsonvt + fs.readFile` inside every single worker

**Comment by mourner** [comment]
The new architecture has all source-related code in separate files and pluggable, so it will be easy.

**Comment by mourner** [comment]
@tcql for the specific task you're talking about, what I would do is split the jobs by country, running a separate job on each country polygon, and then just disregard the error introduced by tiles that are on country borders because they won't affect results much (the bulk of the data is in cities, not on borders, and there are many more tiles inside the country than on the border).

To fix the trouble of watchbot splitting jobs by big tiles, I suggest waiting till I push next-gen tile-reduce and trying that on a local machine — it should be fast enough. :)

**Comment by mourner** [comment]
Since the country thing was dealt other way and tilelive sources don't seem worth implementing atm, let's close this and then open a separate ticket for each source we want to consider implementing (e.g. raster PNG/JPG tiles).
