### ISSUE TITLE
Nextgen: dealing with interleaved stdout output

### ISSUE THREAD

**Issue by mourner** [mapbox/tile-reduce#52]
I think I have a good plan for the interleaved output bug. It's clear that we need to pipe processes to the main thread so that the output is done by a single process. My luck with diff on Node 0.12 was probably due to its new feature of stream corking/uncorking (buffering writes) by default, which possibly made the actual writes to stdout happen less often.

Even when piping, many worker streams are still piped to stdout at the same time and each worker pipes buffer chunks instead of logical pieces of output, so interleaved output still happens. To fix it, we need to make sure that we pipe to stdout in logical bits so that output from one tile is never split into several chunks. 

We can do that by splitting each stream on tile-by-tile basis before piping to main stdout. Splitting by linebreaks is not ideal since you may not have linebreaks at all (e.g. if you use `process.stdout.write` in each tile), and you may have many linebreaks in each tile output which we don't want to split by (it can get interleaved). Additionally, after you split, you have to readd a linebreak to each chunk which is an additional performance overhead. 

Instead, we could manually write an RS ASCII character (`0x1e`, borrowed from [JSON text sequences spec](https://tools.ietf.org/html/rfc7464)) after each map fn run in `worker.js`, and then split by the character. This way we split only per tile, and do not have to append anything to each chunk. Additionally, we can minimize the performance overhead of splitting by using [binary-split](https://github.com/maxogden/binary-split) instead of `split`, since we don't need string conversion to control the output.

The only limitation that we'd have to impose with this approach is stating in the docs that you MUST output anything just before calling the `done` callback (and not in a different process tick if the map function is async). 

Alternatively, we could introduce a special API, e.g. another argument to `done` like this:

```js
module.exports = function(data, tile, done) {
  done(null, data.osm.osm.length, "My output");
};
```

Another future problem that may arise is when you want to stream binary output (which may contain `0x1e` byte), e.g. streaming PNG raster files. But you could probably deal with this in an alternative way, e.g. providing an option to split by a different sequence of characters (each PNG starts with a [unique set of bytes](http://www.libpng.org/pub/png/spec/1.2/PNG-Structure.html)).

This is a tricky problem to tackle, but this seems like an acceptable solution.

cc @tcql @morganherlocker

**Comment by tcql** [comment]
I've got a bunch of [tests for resolving interleaving](https://github.com/tcql/test-worker-writes), including using a record separator. 

I found that using a record separator between each log/write instead of a single one for the entire map function worked much better when writing large amounts of results from the map worker. In my testing examples, I was writing 20,000 geojson features in each map function, which is probably much more than most people  would be doing, but still good to keep in mind. 

Here's the breakdown of performance, just doing a couple of quick `time node index.js` runs for each option

Type | Repo Test Folder | Time
--- | --- | ---
IPC Messaging, Individual Records, JSON | messaging-single | 31s
IPC Messaging, Individual Records, String | messaging-single-strings | 11s
IPC Messaging, Once per Map, JSON | messaging-bulk | 2m51s
IPC Messaging, Once per Map, String | messaging-bulk-strings | 2m28s
Pipe stdout to files, concat at end | pipe-to-parent-and-files | 5-6s
Record Separator between writes | binary-split-character | 6-7s

Looks like files is slightly faster than the intermediary split stream, but comes with it's own issues:
- where do you put the temp files? 
- what do you name them to prevent collisions? 
- you have to also do cleanup, which will result in a small time penalty, especially for large outputs
- you have to have enough disk space for 2x your result output to store the temp worker files and the final output before you clean up the temp files

## summary 

Record separators are probably the best balance of simple / fast, they will just require us to supply users with a write function if we want to use separators per record/message. If we want separators per call to the map function, we need to be very mindful about writing large amounts of data. IMO, a write function is a better and safer idea, especially if we don't want to make any assumptions about what type of machines will be running tile-reduce

**Comment by tcql** [comment]
Separators + write function are in 87abcc8
